### ISSUE TITLE
Debug only validation errors when window is resized during path tracing

### ISSUE THREAD

**Issue by viviicat** [gheshu/pim#19]
- Enable path tracing
- Resize or unmaximize window
- assert in `bool vkrBuffer_Write()`, can continue
- then vulkan repeatedly reports:
```Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x202cb153b78, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | Submitted command buffer expects VkImage 0x5afa4900000004fe[] (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.```

**Comment by gheshu** [comment]
I'll change the assert to >= 0 && <= size rather than == size, since vkrBuffer_Reserve will only grow a buffer and the assert fires when shrinking the window size.

The validation error should not cause a crash. You should be able to F5 past it.
I need to implement some state tracking that can handle raw VkImage handles & is aware of layout changes by/for VkRenderPass.

**Comment by viviicat** [comment]
Last I checked there were repeated errors after the initial assert

**Comment by gheshu** [comment]
Yeah it will log a validation message for each image in the framebuffer, for each framebuffer in the swapchain, 9 times total I believe.
